// Defines the structure of a single task.
export interface Task {
  ID: string;
  Title: string;
  DueISO: string;
  Priority: 'H' | 'M' | 'L';
  EstPom: number;
  SpentPom: number;
  Status: 'todo' | 'doing' | 'done';
}

// Defines the structure for creating a new task, omitting fields generated by the backend.
export type NewTask = Omit<Task, 'ID' | 'SpentPom' | 'Status'>;
